name: Build and push to GHCR

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"
      - "v[0-9]+.[0-9]+"
      - "v*"

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:

  build-and-push-dockerimages:
    strategy:
      fail-fast: false

      matrix:
        project: [frontend]
    secrets:
      IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
    uses: Calance-US/calance-workflows/.github/workflows/build.yml@v3.0.0

    with:
    
      image_name: ${{ matrix.project }}

      image_registry: ${{ vars.IMAGE_REGISTRY }}

      image_registry_username: ${{ vars.IMAGE_REGISTRY_USERNAME }}

      docker_context_path: frontend/

      dockerfile_path: frontend/Dockerfile

