name: Continuous integration and delivery
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Run generic CI-CD workflow
        uses: Calance-US/calance-workflows/.github/workflows/build.yml@main
