name: Build and push to GHCR

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"
      - "v[0-9]+.[0-9]+"
      - "v*"

  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: calance-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:

  build-and-push-dockerimages:
    strategy:
      fail-fast: false

      matrix:
        project: [frontend]

    uses: Calance-US/calance-workflows/.github/workflows/build.yml@v3.0.0

    with:
      image_name: calance-us/${{ matrix.project }}

      image_registry: ${{ vars.IMAGE_REGISTRY }}

      image_registry_username: ${{ vars.IMAGE_REGISTRY_USERNAME }}

      docker_context_path: frontend/

      dockerfile_path: frontend/Dockerfile

    secrets:
      IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}